---
daemon:
    serviceAccountName: "honeydipper"
    env:
        - name: REPO
          value: https://github.com/Charles546/testhoneydipper.git
        - name: BRANCH
          value: main
        - name: SLACK_TOKEN
          valueFrom:
              secretKeyRef:
                  name: slack-secret
                  key: TOKEN
        - name: SLASH_TOKEN
          valueFrom:
              secretKeyRef:
                  name: slack-secret
                  key: SLASH_TOKEN
    image:
        repository: charleshoney/honeydipper
        tag: 2.8.1-patched
drivers:
    redis:
        local: false

